name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.3.1
  just_audio: ^0.9.30
  # <-- Reklam paketi buraya eklendi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/audio/arkaplanmuzik.mp3
    - assets/images/ajanbaslangic.png
    - assets/images/ajanfoto.png
    - assets/images/ajan.png
    - assets/images/köylü.png
    - assets/icon/ajanfoto.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ajanfoto.png"

