// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdDNu60bz9VGU5fO6vzIXBkJN7cghioog',
    appId: '1:797189190759:web:8b04db83be54a28d2890c2',
    messagingSenderId: '797189190759',
    projectId: 'bukim-1a232',
    authDomain: 'bukim-1a232.firebaseapp.com',
    databaseURL: 'https://bukim-1a232-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bukim-1a232.firebasestorage.app',
    measurementId: 'G-HFERYVSJZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwmqUSiNKAHitMIgz9uEcvANVdJ2vafck',
    appId: '1:797189190759:android:16d2982e55aa714d2890c2',
    messagingSenderId: '797189190759',
    projectId: 'bukim-1a232',
    databaseURL: 'https://bukim-1a232-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bukim-1a232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAibOjEFviPyyYbnla1U2gixr1nTsQyxkU',
    appId: '1:797189190759:ios:b10526d8838fb8142890c2',
    messagingSenderId: '797189190759',
    projectId: 'bukim-1a232',
    databaseURL: 'https://bukim-1a232-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bukim-1a232.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAibOjEFviPyyYbnla1U2gixr1nTsQyxkU',
    appId: '1:797189190759:ios:3a035bf911120ef72890c2',
    messagingSenderId: '797189190759',
    projectId: 'bukim-1a232',
    databaseURL: 'https://bukim-1a232-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bukim-1a232.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNCGiMqJO0PkicBeF-0OZyH4Lk4oFm2ps',
    appId: '1:797189190759:web:f459696f087a13822890c2',
    messagingSenderId: '797189190759',
    projectId: 'bukim-1a232',
    authDomain: 'bukim-1a232.firebaseapp.com',
    databaseURL: 'https://bukim-1a232-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bukim-1a232.firebasestorage.app',
    measurementId: 'G-SS1776J2QY',
  );

}